apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: documint-backend
  labels:
    cloud.googleapis.com/location: asia-south1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/documint-backend:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: ALLOWED_ORIGINS
          value: "https://documint-ai-142203089299.asia-south1.run.app,http://localhost:3000,http://127.0.0.1:3000"
        - name: SECRET_KEY
          value: "your-production-secret-key-here"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi